version: '3.4'

services:
  secondary:
    image: secondary
    build:
      context: server-side
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3008:3008
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
